<html>
<head>
<title>Index Project</title>

</head>
<body background="imagen/Fondo.jpg" position:absolute >
<body src=<body bgcolor="grey">
<h1><strong>Index:</strong></h1>
<h2><a href="file:///C:/Users/Jose/Desktop/Prueba/Accesibility%20standars.html">-Accessibility standars.</a></h2>
<h2><a href="file:///C:/Users/Jose/Desktop/Prueba/Digital%20signature.html">-Digital signature.</a></h2>
<h2><a href="file:///C:/Users/Jose/Desktop/Prueba/Internet%20security.html">-Internet Security.</a></h2>
<h2><a href="file:///C:/Users/Jose/Desktop/Prueba/Object%20orientated.html">-Object orientated.</a></h2>

</body>


</html>
